name: Java CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Set up JDK 17
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 17
    - name: Grant permissions
      run: chmod +x gradlew
    - name: Build Skript for 1.12.2
      run: ./gradlew clean build
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Skript
        path: build/libs/*.jar
